### ISSUE TITLE
webgl-demo.js: makePerspective not defined

### ISSUE THREAD

**Issue by jeroldhaas** [mdn/webgl-examples#10]
In function drawScene.

Issue is a show stopper.

**Comment by jeroldhaas** [comment]
I assume this is an external dependency from Sylvester or glUtils. Seeing as it appears to be the only one, it may be best for the tutorial's sake (at https://developer.mozilla.org/en-US/docs/Web/API/) to extract it into source file (with accreditation, of course :) )

**Comment by F1LT3R** [comment]
I am also seeing this. (but only in Chrome) Firefox works fine.

**Comment by JeanPSF** [comment]
this is a problem again aparently, and i can't find the glUtils into the example2 or root folder. Did it change?
