### ISSUE TITLE
If I were to go by this tutorial, it takes over 100 lines to put in a texture, and only WITH a thousand line library attached?

### ISSUE THREAD

**Issue by funkjunky** [mdn/webgl-examples#14]
OpenGL with SDL was easier than this decades ago in C++.

Is there no simpler way to write a texture on a canvas in javascript?

**Comment by greggman** [comment]
First of your complaint is kind of ridiculous. You're complaining about a 1k line math library but you're comparing it to SDL which is a 180k line library!!

You want to write an image on a canvas in JavaScript it's

    const ctx = someCanvas.getContext("2d");
    const img = new Image();
    img.onload = () => {
       ctx.drawImage(img, 0, 0);
    }
    img.src = "path/to/image";

No libraries required

If you want to do it in WebGL then [here's an example](https://webglfundamentals.org/webgl/lessons/webgl-image-processing.html)

**Comment by funkjunky** [comment]
That example is exactly what I was looking for. [The linked example, because I want to apply a shader to the image]

That seems so much simpler than https://github.com/mdn/webgl-examples/blob/gh-pages/tutorial/sample2/webgl-demo.js

Thank you. I'll close this as you've solved my problem.
