### ISSUE TITLE
Rewriting these examples?

### ISSUE THREAD

**Issue by greggman** [mdn/webgl-examples#17]
who's in charge here? I'd like to get permission to make some very large changes. But I don't want to spent 40+ hours re-writing them if they'll just be rejected so I thought I'd ask first.

These lessons seem to have many issues. Some minor, some less minor

Here's some of the things I'd like to change

*  Use modern HTML

    That means for example

    * put script tags at the bottom of the file, no need for `onload="start()"` because you can just execute code at the bottom. 
    * Use `<meta charset="utf-8">` not the old `meta http-equiv` way
    * remove the unneeded `type="text/javascript"` from script tags
    * remove the `canvas not supported` stuff left over from when that may have mattered

* Replace sylvester.js with gl-matrix.js

    sylvester is not a popular library. It's a also not really suited for WebGL given it stores matrices as arrays of arrays which have to then be flattened. I'm not personally a fan of gl-matrix but it is popular.

* Remove the magic

    The 2nd article uses lots of magic math and magic globals. Instead, make the 2nd article
    not use any math and move the 2nd to the 3rd and while not explaining the math (since that wasn't a goal) at least
    refactor to make it less magic and use less globals

* use `requestAnimationFrame` instead of `setInterval`. 

   This seems left over from pre `requestAnimationFrame` days. It should just be removed

* don't use an animation loop for examples that are not animated

* fix the rotation in the first few rotation samples that is extremely strange (go look the samples to see what I mean)

* look up uniform locations before using them instead of every time

* use `document.querySelector` not `document.getElementById` (not bad per-se, just old)

* don't use `experimental-webgl` anymore. AFAIK it's only used in IE11 and that version of WebGL has many bugs. Since only experts are likely to workaround the bugs there's really no reason to keep using it unless you're an expert capable of working around those bugs

* use `const` where appropriate

* change the code that gets script content for shaders from iterating through elements to use using `scriptTag.text` (or consider using multiline-template literals for shaders are available everywhere except IE.)

* Of course also refactor the articles on MDN once these changes are made.

[Here's an example of some of the proposed changes](https://github.com/mdn/webgl-examples/compare/gh-pages...greggman:example-changes?expand=1)

**Comment by Elchi3** [comment]
Hi! Thanks for your interest in modernizing the WebGL examples. This repo supports the documentation / the tutorial at https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/Tutorial and it has indeed aged quite well at this point. Ideally, the documentation and the example code here should be modernized at the same time. 

> who's in charge here?
That's the MDN community and probably especially the MDN full time contributors paid by Mozilla. I can try to review this, but as with all large change sets, review might take some time. This is also not a project I had planned to dedicate time to currently. But I will try to get back to you or attempt to find people with WebGL knowledge that could review, too!

Thanks again for considering to contribute to MDN.

**Comment by greggman** [comment]
yes of course I'd update both..

do you have commit rights? in other words are you telling me if I spend the time you will review and hopefully accept the pull requests? 

I will update both but one has to be done before the other. i'd suggest the code first

**Comment by Elchi3** [comment]
Yes, I have commit rights. I will try to review (or find someone to review) as said above.
Updating the code first sounds alright to me.
