### ISSUE TITLE
first code sample is missing the "window.onload = main;" line at the bottom to actually load the box

### ISSUE THREAD

**Issue by Myles-Damon** [mdn/webgl-examples#26]
Though the tutorial mentions the "window.onload = main;", the code here does not have it. The canvas/box does not load if this isn't added for me using Firefox

**Comment by schalkneethling** [comment]
Hey @Myles-Damon, thank you for filing the issue. I do see that right at the beginning of the Javascript block there is a call to `main()`. I also do see the block box in both Firefox and Chrome. With that said, I do agree that the code should follow what is stated in the tutorial so, I will open a pull request to make that change.
