### ISSUE TITLE
Matrix, Vector, $M are undefined...

### ISSUE THREAD

**Issue by Nisk** [mdn/webgl-examples#4]
In: webgl-examples/tutorial/sample2/webgl-demo.js

So the demo doesn't run.

Using global variables everywhere, in my opinion, makes the tutorial harder to follow - simply by not declaring a variable when it's needed and passing it to the function that needs it - creates a disjoint between what's where and used for what. If you separate the conceptual tasks, of loading shaders, drawing scenes - it's a good idea to couple the variables needed for that - to that section.

Looking forward to finishing the tutorial.

**Comment by AndersBillLinden** [comment]
Which browser? It runs all fine on chrome for me. Change the code and issue a pull request to make it better.

**Comment by bnjm** [comment]
Just to expand on this, as I ran into the same - the undefined methods are coming from the glUtils.js file. When you're following the tutorial along sequentially it's not clear that this file needs to be included for the demo to run, and it's confusing when it doesn't. 

Great tutorial otherwise 👍

**Comment by Nisk** [comment]
Yes, it is as @bnjm says. I have figured it out since, just didn't have time to update this post, Apologies.
